// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUyVmx1dJmiKzn6o5ZDNTMHp9fUii57XE',
    appId: '1:758964018165:web:b3915d08463d8ff2c05ebc',
    messagingSenderId: '758964018165',
    projectId: 'connexc-1c478',
    authDomain: 'connexc-1c478.firebaseapp.com',
    storageBucket: 'connexc-1c478.appspot.com',
    measurementId: 'G-KNMKWDLCSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsGQjSkBZuhhpR9OorcZl8BWJn_LUuIsE',
    appId: '1:758964018165:android:f777e40e6c112b00c05ebc',
    messagingSenderId: '758964018165',
    projectId: 'connexc-1c478',
    storageBucket: 'connexc-1c478.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAAsJY_DaYI4toNI0jgJNHB7VQHmBt8Tg',
    appId: '1:758964018165:ios:462acbfbc659547bc05ebc',
    messagingSenderId: '758964018165',
    projectId: 'connexc-1c478',
    storageBucket: 'connexc-1c478.appspot.com',
    iosBundleId: 'com.example.connexc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAAsJY_DaYI4toNI0jgJNHB7VQHmBt8Tg',
    appId: '1:758964018165:ios:5dade29a697658f6c05ebc',
    messagingSenderId: '758964018165',
    projectId: 'connexc-1c478',
    storageBucket: 'connexc-1c478.appspot.com',
    iosBundleId: 'com.example.connexc.RunnerTests',
  );
}
